"""Add group_id to chats table

Revision ID: 97b644af0811
Revises: 9f0ba65e526b
Create Date: 2024-09-21 17:25:53.733439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b644af0811'
down_revision: Union[str, None] = '9f0ba65e526b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chats', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('chats', 'sender_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('sender_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('chats', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chats', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
